<?php

return [
    'filters' => [
        // 'search',
        'small',
        'medium',
        'large',
        'shipment',
        '❤️',
    ],
    'games' => [
        'mwiii' => [
            'name' => 'MW III',
        ],
        'bo6' => [
            'name' => 'BO 6',
        ],
    ],
    // filters:
    // 'search', 'small', 'medium', 'large', 'shipment'
    'maps' => [
        // MW III
        [
            'name' => '6 Star',
            'position' => [1, 1],
            'image' => '6-star.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'large', 'yyyyy'],
        ],
        [
            'name' => 'Afghan',
            'position' => [1, 2],
            'image' => 'afghan.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'large', 'yyyyy'],
        ],
        [
            'name' => 'Airborne',
            'position' => [1, 3],
            'image' => 'airborne.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Alley',
            'position' => [1, 4],
            'image' => 'alley.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy'],
        ],
        [
            'name' => 'Arena Shipment',
            'position' => [2, 1],
            'image' => 'arena-shipment.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy', 'shipment'],
        ],
        [
            'name' => 'Bait',
            'position' => [2, 2],
            'image' => 'bait.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Bit-ment',
            'position' => [2, 3],
            'image' => 'bit-ment.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy', 'shipment'],
        ],
        [
            'name' => 'Bitvela',
            'position' => [2, 4],
            'image' => 'bitvela.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Blacksite',
            'position' => [3, 1],
            'image' => 'blacksite.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'yyyyy'],
        ],
        [
            'name' => 'Breenbergh Hotel',
            'position' => [3, 2],
            'image' => 'breenbergh-hotel.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'yyyyy'],
        ],
        [
            'name' => 'Celship',
            'position' => [3, 3],
            'image' => 'celship.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'yyyyy'],
        ],
        [
            'name' => 'Checkpoint',
            'position' => [3, 4],
            'image' => 'checkpoint.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'yyyyy'],
        ],
        [
            'name' => 'Crown Raceway',
            'position' => [4, 1],
            'image' => 'crown-raceway.jpg',
            'games' => ['mwiii', 'mwii'],
            'filters' => ['search', 'yyyyy'],
        ],
        [
            'name' => 'Das Gross',
            'position' => [4, 2],
            'image' => 'das-gross.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'yyyyy'],
        ],
        [
            'name' => 'Das Haus',
            'position' => [4, 3],
            'image' => 'das-haus.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'yyyyy'],
        ],
        [
            'name' => 'Departures',
            'position' => [4, 4],
            'image' => 'departures.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'yyyyy'],
        ],
        [
            'name' => 'Derail',
            'position' => [5, 1],
            'image' => 'derail.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'yyyyy'],
        ],
        [
            'name' => 'Dome',
            'position' => [5, 2],
            'image' => 'dome.jpg',
            'games' => ['mwiii', 'mwii'],
            'filters' => ['search', 'yyyyy'],
        ],
        [
            'name' => 'Drive Thru',
            'position' => [5, 3],
            'image' => 'drive-thru.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'yyyyy'],
        ],
        [
            'name' => 'Emergency',
            'position' => [5, 4],
            'image' => 'emergency.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'yyyyy'],
        ],
        [
            'name' => 'Estate',
            'position' => [6, 1],
            'image' => 'estate.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Exhibit',
            'position' => [6, 2],
            'image' => 'exhibit.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy'],
        ],
        [
            'name' => 'Farm 18',
            'position' => [6, 3],
            'image' => 'farm-18.jpg',
            'games' => ['mwiii', 'mwii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Favela',
            'position' => [6, 4],
            'image' => 'favela.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'G3T_H1GH',
            'position' => [7, 1],
            'image' => 'g3t_h1gh.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Ghost Ship',
            'position' => [7, 2],
            'image' => 'ghost-ship.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'yyyyy'],
        ],
        [
            'name' => 'Greece',
            'position' => [7, 3],
            'image' => 'greece.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy'],
        ],
        [
            'name' => 'Grime',
            'position' => [7, 4],
            'image' => 'grime.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Growhouse',
            'position' => [8, 1],
            'image' => 'growhouse.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy'],
        ],
        [
            'name' => 'Hangover',
            'position' => [8, 2],
            'image' => 'hangover.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Highrise',
            'position' => [8, 3],
            'image' => 'highrise.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Incline',
            'position' => [8, 4],
            'image' => 'incline.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Ink House',
            'position' => [9, 1],
            'image' => 'ink-house.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy'],
        ],
        [
            'name' => 'Invasion',
            'position' => [9, 2],
            'image' => 'invasion.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'large', 'yyyyy'],
        ],
        [
            'name' => 'Karachi',
            'position' => [9, 3],
            'image' => 'karachi.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'large', 'yyyyy'],
        ],
        [
            'name' => 'Mad Cow',
            'position' => [9, 4],
            'image' => 'mad-cow.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy'],
        ],
        [
            'name' => 'Meat',
            'position' => [10, 1],
            'image' => 'meat.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy'],
        ],
        [
            'name' => 'Mercado Las Almas',
            'position' => [10, 2],
            'image' => 'mercado-las-almas.jpg',
            'games' => ['mwiii', 'mwii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Paris',
            'position' => [10, 3],
            'image' => 'paris.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Quarry',
            'position' => [10, 4],
            'image' => 'quarry.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'large', 'yyyyy'],
        ],
        [
            'name' => 'Rio',
            'position' => [11, 1],
            'image' => 'rio.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Rundown',
            'position' => [11, 2],
            'image' => 'rundown.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'large', 'yyyyy'],
        ],
        [
            'name' => 'Rust',
            'position' => [11, 3],
            'image' => 'rust.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy'],
        ],
        [
            'name' => "Satan's Quarry",
            'position' => [11, 4],
            'image' => 'satans-quarry.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Scrapyard',
            'position' => [12, 1],
            'image' => 'scrapyard.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Shipmas',
            'position' => [12, 2],
            'image' => 'shipmas.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'shipment'],
        ],
        [
            'name' => 'Shipment',
            'position' => [12, 3],
            'image' => 'shipment.jpg',
            'games' => ['mwiii', 'mwii'],
            'filters' => ['search', 'small', 'shipment'],
        ],
        [
            'name' => 'Shoot House',
            'position' => [12, 4],
            'image' => 'shoot-house.jpg',
            'games' => ['mwiii', 'mwii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Skidgrow',
            'position' => [13, 1],
            'image' => 'skidgrow.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Skidrow',
            'position' => [13, 2],
            'image' => 'skidrow.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Sporeyard',
            'position' => [13, 3],
            'image' => 'sporeyard.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Stash House',
            'position' => [13, 4],
            'image' => 'stash-house.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy'],
        ],
        [
            'name' => 'Stay High',
            'position' => [14, 1],
            'image' => 'stay-high.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'shipment'],
        ],
        [
            'name' => 'Sub Base',
            'position' => [14, 2],
            'image' => 'sub-base.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'large', 'yyyyy'],
        ],
        [
            'name' => 'Sunny Shipment',
            'position' => [14, 3],
            'image' => 'sunny-shipment.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'shipment'],
        ],
        [
            'name' => 'Tanked',
            'position' => [14, 4],
            'image' => 'tanked.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'large', 'yyyyy'],
        ],
        [
            'name' => 'Terminal',
            'position' => [15, 1],
            'image' => 'terminal.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Tetanus',
            'position' => [15, 2],
            'image' => 'tetanus.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy'],
        ],
        [
            'name' => 'Tokyo',
            'position' => [15, 3],
            'image' => 'tokyo.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Toonoxide',
            'position' => [15, 4],
            'image' => 'toonoxide.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy'],
        ],
        [
            'name' => 'Training Facility',
            'position' => [16, 1],
            'image' => 'training-facility.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'small', 'yyyyy'],
        ],
        [
            'name' => 'Underpass',
            'position' => [16, 2],
            'image' => 'underpass.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'large', 'yyyyy'],
        ],
        [
            'name' => 'Vista',
            'position' => [16, 3],
            'image' => 'vista.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],
        [
            'name' => 'Wasteland',
            'position' => [16, 4],
            'image' => 'wasteland.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'large', 'yyyyy'],
        ],
        [
            'name' => 'Yard',
            'position' => [17, 1],
            'image' => 'yard.jpg',
            'games' => ['mwiii'],
            'filters' => ['search', 'medium', 'yyyyy'],
        ],

        // BO6
        [
            'name' => 'Babylon',
            'position' => [17, 1],
            'image' => 'babylon.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'medium'],
        ],
        [
            'name' => 'Derelict',
            'position' => [17, 1],
            'image' => 'derelict.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'medium'],
        ],
        [
            'name' => 'Extraction',
            'position' => [17, 1],
            'image' => 'extraction.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'medium'],
        ],
        [
            'name' => 'Gala',
            'position' => [17, 1],
            'image' => 'gala.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'small'],
        ],
        [
            'name' => 'Hacienda',
            'position' => [17, 1],
            'image' => 'hacienda.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'large'],
        ],
        [
            'name' => 'Heirloom',
            'position' => [17, 1],
            'image' => 'heirloom.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'small'],
        ],
        [
            'name' => 'Hideout',
            'position' => [17, 1],
            'image' => 'hideout.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'medium'],
        ],
        [
            'name' => 'Lowtown',
            'position' => [17, 1],
            'image' => 'lowtown.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'large'],
        ],
        [
            'name' => 'Payback',
            'position' => [17, 1],
            'image' => 'payback.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'small'],
        ],
        [
            'name' => 'Pit',
            'position' => [17, 1],
            'image' => 'pit.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'small'],
        ],
        [
            'name' => 'Protocol',
            'position' => [17, 1],
            'image' => 'protocol.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'medium'],
        ],
        [
            'name' => 'Racket',
            'position' => [17, 1],
            'image' => 'racket.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'small'],
        ],
        [
            'name' => 'Red Card',
            'position' => [17, 1],
            'image' => 'red-card.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'large'],
        ],
        [
            'name' => 'Rewind',
            'position' => [17, 1],
            'image' => 'rewind.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'medium'],
        ],
        [
            'name' => 'Scud',
            'position' => [17, 1],
            'image' => 'scud.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'medium'],
        ],
        [
            'name' => 'Skyline',
            'position' => [17, 1],
            'image' => 'skyline.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'medium'],
        ],
        [
            'name' => 'Stakeout',
            'position' => [17, 1],
            'image' => 'stakeout.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'small'],
        ],
        [
            'name' => 'Subsonic',
            'position' => [17, 1],
            'image' => 'subsonic.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'medium'],
        ],
        [
            'name' => 'Vault',
            'position' => [17, 1],
            'image' => 'vault.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'large'],
        ],
        [
            'name' => 'Vorkuta',
            'position' => [17, 1],
            'image' => 'vorkuta.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'large'],
        ],
        [
            'name' => 'Warhead',
            'position' => [17, 1],
            'image' => 'warhead.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'small'],
        ],
        [
            'name' => 'Bounty',
            'position' => [17, 1],
            'image' => 'bounty.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop','medium'],
        ],
        [
            'name' => 'Bullet',
            'position' => [17, 1],
            'image' => 'bullet.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'small'],
        ],
        [
            'name' => 'Dealership',
            'position' => [17, 1],
            'image' => 'dealership.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'large'],
        ],
        [
            'name' => 'Grind',
            'position' => [17, 1],
            'image' => 'grind.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'medium'],
        ],
        [
            'name' => 'Lifeline',
            'position' => [17, 1],
            'image' => 'lifeline.jpg',
            'games' => ['bo6'],
            'filters' => ['search', 'prop', 'small'],
        ],
    ],
];
