<?php

return [
    ['name' => '6 Star', 'position' => [1, 1]],
    ['name' => 'Afghan', 'position' => [1, 2]],
    ['name' => 'Airborne', 'position' => [1, 3]],
    ['name' => 'Alley', 'position' => [1, 4]],
    ['name' => 'Arena Shipment', 'position' => [2, 1]],
    ['name' => 'Bait', 'position' => [2, 2]],
    ['name' => 'Bit-ment', 'position' => [2, 3]],
    ['name' => 'Bitvela', 'position' => [2, 4]],
    ['name' => 'Blacksite', 'position' => [3, 1]],
    ['name' => 'Breenbergh Hotel', 'position' => [3, 2]],
    ['name' => 'Celship', 'position' => [3, 3]],
    ['name' => 'Checkpoint', 'position' => [3, 4]],
    ['name' => 'Crown Raceway', 'position' => [4, 1]],
    ['name' => 'Das Gross', 'position' => [4, 2]],
    ['name' => 'Das Haus', 'position' => [4, 3]],
    ['name' => 'Departures', 'position' => [4, 4]],
    ['name' => 'Derail', 'position' => [5, 1]],
    ['name' => 'Dome', 'position' => [5, 2]],
    ['name' => 'Drive Thru', 'position' => [5, 3]],
    ['name' => 'Emergency', 'position' => [5, 4]],
    ['name' => 'Estate', 'position' => [6, 1]],
    ['name' => 'Exhibit', 'position' => [6, 2]],
    ['name' => 'Farm 18', 'position' => [6, 3]],
    ['name' => 'Favela', 'position' => [6, 4]],
    ['name' => 'Get High', 'position' => [7, 1]],
    ['name' => 'Ghost Ship', 'position' => [7, 2]],
    ['name' => 'Greece', 'position' => [7, 3]],
    ['name' => 'Grime', 'position' => [7, 4]],
    ['name' => 'Growhouse', 'position' => [8, 1]],
    ['name' => 'Hangover', 'position' => [8, 2]],
    ['name' => 'Highrise', 'position' => [8, 3]],
    ['name' => 'Incline', 'position' => [8, 4]],
    ['name' => 'Ink House', 'position' => [9, 1]],
    ['name' => 'Invasion', 'position' => [9, 2]],
    ['name' => 'Karachi', 'position' => [9, 3]],
    ['name' => 'Mad Cow', 'position' => [9, 4]],
    ['name' => 'Meat', 'position' => [10, 1]],
    ['name' => 'Mercado Las Almas', 'position' => [10, 2]],
    ['name' => 'Paris', 'position' => [10, 3]],
    ['name' => 'Quarry', 'position' => [10, 4]],
    ['name' => 'Rio', 'position' => [11, 1]],
    ['name' => 'Rundown', 'position' => [11, 2]],
    ['name' => 'Rust', 'position' => [11, 3]],
    ['name' => "Satan's Quarry", 'position' => [11, 4]],
    ['name' => 'Scrapyard', 'position' => [12, 1]],
    ['name' => 'Shipmas', 'position' => [12, 2]],
    ['name' => 'Shipment', 'position' => [12, 3]],
    ['name' => 'Shoot House', 'position' => [12, 4]],
    ['name' => 'Skidgrow', 'position' => [13, 1]],
    ['name' => 'Skidrow', 'position' => [13, 2]],
    ['name' => 'Sporeyard', 'position' => [13, 3]],
    ['name' => 'Stash House', 'position' => [13, 4]],
    ['name' => 'Stay High', 'position' => [14, 1]],
    ['name' => 'Sub Base', 'position' => [14, 2]],
    ['name' => 'Sunny Shipment', 'position' => [14, 3]],
    ['name' => 'Tanked', 'position' => [14, 4]],
    ['name' => 'Terminal', 'position' => [15, 1]],
    ['name' => 'Tetanus', 'position' => [15, 2]],
    ['name' => 'Tokyo', 'position' => [15, 3]],
    ['name' => 'Toonoxide', 'position' => [15, 4]],
    ['name' => 'Training Facility', 'position' => [16, 1]],
    ['name' => 'Underpass', 'position' => [16, 2]],
    ['name' => 'Vista', 'position' => [16, 3]],
    ['name' => 'Wasteland', 'position' => [16, 4]],
    ['name' => 'Yard', 'position' => [17, 1]],
];
