<?php

return [
    [
        'name' => '6 Star',
        'position' => [1, 1],
        'image' => '6-star.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Afghan',
        'position' => [1, 2],
        'image' => 'afghan.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Airborne',
        'position' => [1, 3],
        'image' => 'airborne.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Alley',
        'position' => [1, 4],
        'image' => 'alley.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Arena Shipment',
        'position' => [2, 1],
        'image' => 'arena-shipment.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Bait',
        'position' => [2, 2],
        'image' => 'bait.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Bit-ment',
        'position' => [2, 3],
        'image' => 'bit-ment.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Bitvela',
        'position' => [2, 4],
        'image' => 'bitvela.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Blacksite',
        'position' => [3, 1],
        'image' => 'blacksite.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Breenbergh Hotel',
        'position' => [3, 2],
        'image' => 'breenbergh-hotel.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Celship',
        'position' => [3, 3],
        'image' => 'celship.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Checkpoint',
        'position' => [3, 4],
        'image' => 'checkpoint.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Crown Raceway',
        'position' => [4, 1],
        'image' => 'crown-raceway.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Das Gross',
        'position' => [4, 2],
        'image' => 'das-gross.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Das Haus',
        'position' => [4, 3],
        'image' => 'das-haus.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Departures',
        'position' => [4, 4],
        'image' => 'departures.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Derail',
        'position' => [5, 1],
        'image' => 'derail.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Dome',
        'position' => [5, 2],
        'image' => 'dome.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Drive Thru',
        'position' => [5, 3],
        'image' => 'drive-thru.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Emergency',
        'position' => [5, 4],
        'image' => 'emergency.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Estate',
        'position' => [6, 1],
        'image' => 'estate.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Exhibit',
        'position' => [6, 2],
        'image' => 'exhibit.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Farm 18',
        'position' => [6, 3],
        'image' => 'farm-18.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Favela',
        'position' => [6, 4],
        'image' => 'favela.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Get High',
        'position' => [7, 1],
        'image' => 'get-high.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Ghost Ship',
        'position' => [7, 2],
        'image' => 'ghost-ship.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Greece',
        'position' => [7, 3],
        'image' => 'greece.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Grime',
        'position' => [7, 4],
        'image' => 'grime.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Growhouse',
        'position' => [8, 1],
        'image' => 'growhouse.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Hangover',
        'position' => [8, 2],
        'image' => 'hangover.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Highrise',
        'position' => [8, 3],
        'image' => 'highrise.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Incline',
        'position' => [8, 4],
        'image' => 'incline.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Ink House',
        'position' => [9, 1],
        'image' => 'ink-house.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Invasion',
        'position' => [9, 2],
        'image' => 'invasion.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Karachi',
        'position' => [9, 3],
        'image' => 'karachi.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Mad Cow',
        'position' => [9, 4],
        'image' => 'mad-cow.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Meat',
        'position' => [10, 1],
        'image' => 'meat.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Mercado Las Almas',
        'position' => [10, 2],
        'image' => 'mercado-las-almas.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Paris',
        'position' => [10, 3],
        'image' => 'paris.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Quarry',
        'position' => [10, 4],
        'image' => 'quarry.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Rio',
        'position' => [11, 1],
        'image' => 'rio.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Rundown',
        'position' => [11, 2],
        'image' => 'rundown.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Rust',
        'position' => [11, 3],
        'image' => 'rust.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => "Satan's Quarry",
        'position' => [11, 4],
        'image' => 'satans-quarry.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Scrapyard',
        'position' => [12, 1],
        'image' => 'scrapyard.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Shipmas',
        'position' => [12, 2],
        'image' => 'shipmas.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Shipment',
        'position' => [12, 3],
        'image' => 'shipment.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Shoot House',
        'position' => [12, 4],
        'image' => 'shoot-house.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Skidgrow',
        'position' => [13, 1],
        'image' => 'skidgrow.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Skidrow',
        'position' => [13, 2],
        'image' => 'skidrow.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Sporeyard',
        'position' => [13, 3],
        'image' => 'sporeyard.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Stash House',
        'position' => [13, 4],
        'image' => 'stash-house.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Stay High',
        'position' => [14, 1],
        'image' => 'stay-high.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Sub Base',
        'position' => [14, 2],
        'image' => 'sub-base.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Sunny Shipment',
        'position' => [14, 3],
        'image' => 'sunny-shipment.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Tanked',
        'position' => [14, 4],
        'image' => 'tanked.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Terminal',
        'position' => [15, 1],
        'image' => 'terminal.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Tetanus',
        'position' => [15, 2],
        'image' => 'tetanus.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Tokyo',
        'position' => [15, 3],
        'image' => 'tokyo.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Toonoxide',
        'position' => [15, 4],
        'image' => 'toonoxide.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Training Facility',
        'position' => [16, 1],
        'image' => 'training-facility.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Underpass',
        'position' => [16, 2],
        'image' => 'underpass.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Vista',
        'position' => [16, 3],
        'image' => 'vista.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Wasteland',
        'position' => [16, 4],
        'image' => 'wasteland.jpg',
        'games' => ['mwiii'],
    ],
    [
        'name' => 'Yard',
        'position' => [17, 1],
        'image' => 'yard.jpg',
        'games' => ['mwiii'],
    ],
];
